'use client';

import { useEffect, useState } from 'react';
import { Navigation } from '@/components/navigation';
import { PageHeader } from '@/components/page-header';
import { Card, Button, Input, Select, Badge } from '@/components/ui';
import { fetchOperations, createOperation, deleteOperation, fetchAccounts, fetchVehicleDefinitions } from '@/lib/api';
import { useRequireAuth } from '@/lib/hooks';
import { Account, Reception, VehicleDefinition } from '@/lib/types';
import { formatDate, formatCurrency } from '@/lib/utils';
import { clsx } from 'clsx';

export default function ReceptionsPage() {
  const { loading: authLoading } = useRequireAuth();
  const [operations, setOperations] = useState<Reception[]>([]);
  const [livraisons, setLivraisons] = useState<Reception[]>([]); // New state for checking sales
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [vehicleDefs, setVehicleDefs] = useState<VehicleDefinition[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [formData, setFormData] = useState({
    account_id: '',
    date_operation: '',
    type_operation: 'reception' as const,
    quantite: 1,
    prix_total_achat: 0, // Used for input: Total User Pays
    commission: 0,
    prix_base: 0, // Calculated: Total - Commission
    marque: '',
    modele: '',
  });

  const [vins, setVins] = useState<string[]>(['']);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!authLoading) {
      loadData();
    }
  }, [authLoading]);

  // VIN generation
  useEffect(() => {
    const qty = Math.max(1, Math.floor(formData.quantite));
    setVins(prev => {
      if (qty === prev.length) return prev;
      if (qty > prev.length) return [...prev, ...Array(qty - prev.length).fill('')];
      return prev.slice(0, qty);
    });
  }, [formData.quantite]);

  // Pricing Logic: Base Price = Total Price - Commission
  useEffect(() => {
    const total = formData.prix_total_achat || 0;
    const comm = formData.commission || 0;
    setFormData(prev => ({ ...prev, prix_base: total - comm }));
  }, [formData.prix_total_achat, formData.commission]);

  async function loadData() {
    try {
      const [ops, accs, defs] = await Promise.all([
        fetchOperations(),
        fetchAccounts(),
        fetchVehicleDefinitions()
      ]);
      setOperations(ops.filter((op) => op.type_operation === 'reception'));
      setLivraisons(ops.filter((op) => op.type_operation === 'livraison')); // Store deliveries
      setAccounts(accs.filter(a => a.type_compte === 'fournisseur')); // Filter only Payers
      setVehicleDefs(defs);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load data');
    } finally {
      setLoading(false);
    }
  }

  const handleVehicleSelect = (defId: string) => {
    const def = vehicleDefs.find(d => d.id === defId);
    if (def) {
      setFormData(prev => ({
        ...prev,
        marque: def.marque,
        modele: def.modele,
        prix_total_achat: def.prix_achat_defaut || 0
      }));
    }
  };

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (isSubmitting) return;
    setIsSubmitting(true);

    try {
      const promises = vins.map(vin =>
        createOperation({
          account_id: formData.account_id,
          date_operation: formData.date_operation,
          type_operation: 'reception',
          marque: formData.marque,
          modele: formData.modele,
          quantite: 1,
          numero_chassis: vin,
          // DB Logic Update: 'montant' is generated (quantite * prix_unitaire).
          // We want Montant = Total Purchase Price. Since Quantite is 1, set prix_unitaire = Total Purchase Price.
          prix_unitaire: isNaN(Number(formData.prix_total_achat)) ? 0 : Number(formData.prix_total_achat),
          // Store Base Price in 'prix_achat' for reference/margin calcs
          prix_achat: isNaN(Number(formData.prix_base)) ? 0 : Number(formData.prix_base),
          commission: isNaN(Number(formData.commission)) ? 0 : Number(formData.commission),
          // DO NOT send 'montant', it is generated by DB
        })
      );

      await Promise.all(promises);

      setFormData({
        account_id: '',
        date_operation: '',
        type_operation: 'reception',
        quantite: 1,
        prix_total_achat: 0,
        commission: 0,
        prix_base: 0,
        marque: '',
        modele: '',
      });
      setVins(['']);
      setShowForm(false);
      await loadData();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Une erreur inconnue est survenue');
      console.error('Submission Error:', err);
      // @ts-ignore
      if (err?.details) setError(`${err.message} - Détails: ${err.details} - Hint: ${err.hint}`);
    } finally {
      setIsSubmitting(false);
    }
  }

  const handleVinChange = (index: number, value: string) => {
    const newVins = [...vins];
    newVins[index] = value;
    setVins(newVins);
  };

  if (authLoading || loading) return <div className="min-h-screen flex items-center justify-center">⏳ Chargement...</div>;

  return (
    <div>
      <Navigation />
      <main className="flex-1 container-modern py-8">
        <PageHeader
          title="Gestion des Réceptions (Stock)"
          subtitle="Enregistrement des véhicules entrants"
          icon="📥"
          action={{ label: '➕ Nouvelle Réception', onClick: () => setShowForm(!showForm) }}
        />

        {error && (
          <div className="mb-6 bg-red-100 border border-red-200 text-red-800 p-4 rounded-xl font-mono text-sm whitespace-pre-wrap">
            ⚠️ ERREUR TECHNIQUE : {error}
          </div>
        )}

        {showForm && (
          <Card title="Entrée en Stock" subtitle="Définition du lot de véhicules" className="card-modern mb-8">
            <form onSubmit={handleSubmit} className="space-y-6">

              {/* Step 1: Supplier & Vehicle Selection */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Select
                  label="Fournisseur"
                  value={formData.account_id}
                  onChange={(e) => setFormData({ ...formData, account_id: e.target.value })}
                  options={accounts.map(a => ({ value: a.id, label: a.nom_compte }))}
                  required
                />
                <Input
                  label="Date"
                  type="date"
                  value={formData.date_operation}
                  onChange={(e) => setFormData({ ...formData, date_operation: e.target.value })}
                  required
                />
              </div>

              {/* Vehicle Catalog Selection */}
              <div className="p-5 bg-indigo-50/50 rounded-xl border border-indigo-100">
                <h4 className="font-semibold text-indigo-900 mb-4">🚙 Véhicule</h4>
                <div className="mb-4">
                  <Select
                    label="Modèle (Catalogue)"
                    value=""
                    onChange={(e) => handleVehicleSelect(e.target.value)}
                    options={[
                      { value: '', label: '-- Sélectionner un modèle --' },
                      ...vehicleDefs.map(d => ({ value: d.id, label: `${d.marque} ${d.modele}` }))
                    ]}
                  />
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 opacity-75">
                  <Input
                    label="Marque"
                    value={formData.marque}
                    onChange={(e) => setFormData({ ...formData, marque: e.target.value })}
                    readOnly
                  />
                  <Input
                    label="Modèle"
                    value={formData.modele}
                    onChange={(e) => setFormData({ ...formData, modele: e.target.value })}
                    readOnly
                  />
                </div>
              </div>

              {/* Pricing Logic (Crucial Update) */}
              <div className="p-5 bg-green-50/50 rounded-xl border border-green-100">
                <h4 className="font-semibold text-green-900 mb-4">💰 Prix & Commission</h4>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-end">
                  <Input
                    label="Prix Achat (DA)"
                    type="number"
                    value={formData.prix_total_achat}
                    onChange={(e) => setFormData({ ...formData, prix_total_achat: parseFloat(e.target.value) })}
                    required
                  />
                  <Input
                    label="Commission (DA)"
                    type="number"
                    value={formData.commission}
                    onChange={(e) => setFormData({ ...formData, commission: parseFloat(e.target.value) })}
                    className="bg-green-100/50 border-green-300 font-semibold"
                  />
                  <div>
                    <label className="block text-sm font-medium text-gray-500 mb-1">Prix de Base (Calculé)</label>
                    <div className="w-full px-4 py-2 bg-gray-100 border border-gray-300 rounded-xl font-mono text-gray-700">
                      {formatCurrency(formData.prix_base)}
                    </div>
                  </div>
                </div>
              </div>

              {/* Multi-VIN */}
              <div className="p-4 bg-gray-50 rounded-xl border border-gray-200">
                <div className="mb-4">
                  <Input
                    label="Quantité"
                    type="number"
                    min="1"
                    max="50"
                    value={formData.quantite}
                    onChange={(e) => setFormData({ ...formData, quantite: parseInt(e.target.value) || 1 })}
                    required
                  />
                </div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Numéros de Châssis (VIN)</label>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3 max-h-48 overflow-y-auto custom-scrollbar p-1">
                  {vins.map((vin, idx) => (
                    <div key={idx} className="flex items-center gap-2">
                      <span className="text-xs font-mono text-gray-400 w-6">#{idx + 1}</span>
                      <Input
                        value={vin}
                        onChange={(e) => handleVinChange(idx, e.target.value)}
                        placeholder="VIN..."
                        className="text-sm font-mono h-9"
                        required
                      />
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex gap-3 pt-4">
                <Button type="submit" variant="primary" size="lg" disabled={isSubmitting} className={clsx("w-full md:w-auto", isSubmitting && "opacity-75")}>
                  {isSubmitting ? '⏳ ...' : '✅ Valider Entrée Stock'}
                </Button>
                <Button type="button" variant="ghost" onClick={() => setShowForm(false)} disabled={isSubmitting}>Annuler</Button>
              </div>
            </form>
          </Card>
        )}

        <Card className="card-modern">
          {operations.length === 0 ? (
            <div className="text-center py-12"><p className="text-gray-500">Aucun véhicule en stock.</p></div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Fournisseur</th>
                    <th>Véhicule</th>
                    <th>VIN</th>
                    <th className="text-right">Prix Total</th>
                    <th className="text-center">Commission</th>
                    <th className="text-center">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {operations.map((op) => {
                    const account = accounts.find((a) => a.id === op.account_id);
                    return (
                      <tr key={op.id}>
                        <td className="font-medium">{formatDate(op.date_operation)}</td>
                        <td>{account?.nom_compte}</td>
                        <td className="font-semibold">{op.marque} {op.modele}</td>
                        <td className="font-mono text-xs">{op.numero_chassis}</td>
                        <td className="text-right font-bold">{formatCurrency(op.montant)}</td>
                        <td className="text-center">
                          {op.commission ? <Badge variant="success">+{formatCurrency(op.commission)}</Badge> : '-'}
                        </td>
                        <td className="text-center">
                          <Button
                            size="sm"
                            variant="danger"
                            onClick={async () => {
                              // Safety Check: Is this VIN sold?
                              // NOW checking against 'livraisons' state which actually contains the sales
                              const isSold = livraisons.some(l => l.numero_chassis === op.numero_chassis);

                              if (isSold) {
                                alert('⛔ Impossible de supprimer cette réception : Ce véhicule a déjà été vendu (Livraison existante).');
                                return;
                              }

                              if (confirm('Supprimer cette réception ?')) {
                                try {
                                  await deleteOperation(op.id);
                                  await loadData();
                                } catch (e) {
                                  console.error(e);
                                  alert('Erreur lors de la suppression');
                                }
                              }
                            }}
                          >
                            🗑️
                          </Button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </Card>
      </main>
    </div>
  );
}
